name: Publish Docker image for app

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and publish the app image
    runs-on: ubuntu-latest

    permissions:  # ðŸ‘ˆ IMPORTANT: enable correct permissions for GITHUB_TOKEN
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and publish the API image
        run: |
          docker build -t ghcr.io/hasanshahriar32/karate_dojo:latest .
          docker push ghcr.io/hasanshahriar32/karate_dojo:latest

    #   - name: Trigger redeployment
    #     run: |
    #       curl https://dokploy.caardify.com/api/deploy/wUsSLqlVJC5zCNF_0L8Jf